# goreleaser.yaml to release a new versions to GitHub. Please, check documentation here: http://goreleaser.com

project_name: "bun_cli"
before:
  hooks:
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
-
  main: ./bun/main.go
  binary: bun
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
archives:
-
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
  format: binary

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

